import bcrypt from 'bcryptjs'

const data = {
    users: [
        {
            name: 'Dusan',
            surname: 'Cvetnic',
            email: 'dcvetnic@mail.com',
            password: bcrypt.hashSync('12345', 8),
            address: 'Adresa 1',
            phone: '0641234567',
            isAdmin: true,
        },
        {
            name: 'Pera',
            surname: 'Peric',
            email: 'pperic@mail.com',
            password: bcrypt.hashSync('11111', 8),
            address: 'Adresa 2',
            phone: '0642345678',
            isAdmin: false,
        },
    ],
    products:[
        {
            name: 'Rolex Submariner',
            category: 'muski',
            image: 'https://b34959663f5a3997bd0d-2668915a1d3a077262c88fab6aa0aa02.ssl.cf3.rackcdn.com/17304427_3_640.jpg',
            price: 11490,
            material: 'oystersteel',
            countInStock: 10,
            brand: 'Rolex',
            rating: 5,
            numReviews: 0,
            description: 'Rolex Submariner 40mm Ceramic Bezel Steel Watch 114060 Box Card. Officially certified chronometer self-winding movement. Stainless steel case 40.0 mm in diameter. Rolex logo on a crown. . Scratch resistant sapphire crystal. Black dial with white luminous inlay hands and hour markers. Special time-lapse unidirectional rotating Cerachrom bezel.',
        },
        {
            name: 'Rolex Submariner gold',
            category: 'muski',
            image: 'https://b34959663f5a3997bd0d-2668915a1d3a077262c88fab6aa0aa02.ssl.cf3.rackcdn.com/17304452_3_640.jpg',
            price: 13520,
            material: 'gold',
            countInStock: 20,
            brand: 'Rolex',
            rating: 5,
            numReviews: 0,
            description: 'Rolex Submariner 40mm Ceramic Bezel Steel Watch 114060 Box Card. Officially certified chronometer self-winding movement. Stainless steel case 40.0 mm in diameter. Rolex logo on a crown. . Scratch resistant sapphire crystal. Black dial with white luminous inlay hands and hour markers. Special time-lapse unidirectional rotating Cerachrom bezel.',
        },
        {
            name: 'Rolex Yacht-master',
            category: 'muski',
            image: 'https://b34959663f5a3997bd0d-2668915a1d3a077262c88fab6aa0aa02.ssl.cf3.rackcdn.com/17303232_3_640.jpg',
            price: 24990,
            material: 'oystersteel',
            countInStock: 0,
            brand: 'Rolex',
            rating: 5,
            numReviews: 0,
            description: 'Rolex Submariner 40mm Ceramic Bezel Steel Watch 114060 Box Card. Officially certified chronometer self-winding movement. Stainless steel case 40.0 mm in diameter. Rolex logo on a crown. . Scratch resistant sapphire crystal. Black dial with white luminous inlay hands and hour markers. Special time-lapse unidirectional rotating Cerachrom bezel.',
        },
        {
            name: 'Rolex Yacht-master gold',
            category: 'muski',
            image: 'https://b34959663f5a3997bd0d-2668915a1d3a077262c88fab6aa0aa02.ssl.cf3.rackcdn.com/17303234_3_640.jpg',
            price: 27990,
            material: 'gold',
            countInStock: 3,
            brand: 'Rolex',
            rating: 5,
            numReviews: 0,
            description: 'Rolex Submariner 40mm Ceramic Bezel Steel Watch 114060 Box Card. Officially certified chronometer self-winding movement. Stainless steel case 40.0 mm in diameter. Rolex logo on a crown. . Scratch resistant sapphire crystal. Black dial with white luminous inlay hands and hour markers. Special time-lapse unidirectional rotating Cerachrom bezel.',
        },
        {
            name: 'Rolex Sky-Dweller',
            category: 'muski',
            image: 'https://b34959663f5a3997bd0d-2668915a1d3a077262c88fab6aa0aa02.ssl.cf3.rackcdn.com/17303417_3_640.jpg',
            price: 25990,
            material: 'oystersteel',
            countInStock: 11,
            brand: 'Rolex',
            rating: 5,
            numReviews: 0,
            description: 'Rolex Submariner 40mm Ceramic Bezel Steel Watch 114060 Box Card. Officially certified chronometer self-winding movement. Stainless steel case 40.0 mm in diameter. Rolex logo on a crown. . Scratch resistant sapphire crystal. Black dial with white luminous inlay hands and hour markers. Special time-lapse unidirectional rotating Cerachrom bezel.',
        },
        {
            name: 'Rolex Sky-Dweller gold',
            category: 'muski',
            image: 'https://b34959663f5a3997bd0d-2668915a1d3a077262c88fab6aa0aa02.ssl.cf3.rackcdn.com/17303827_3_640.jpg',
            price: 29000,
            material: 'gold',
            countInStock: 20,
            brand: 'Rolex',
            rating: 5,
            numReviews: 0,
            description: 'Rolex Submariner 40mm Ceramic Bezel Steel Watch 114060 Box Card. Officially certified chronometer self-winding movement. Stainless steel case 40.0 mm in diameter. Rolex logo on a crown. . Scratch resistant sapphire crystal. Black dial with white luminous inlay hands and hour markers. Special time-lapse unidirectional rotating Cerachrom bezel.',
        },
        {
            name: 'Rolex Day-date gold',
            category: 'muski',
            image: 'https://b34959663f5a3997bd0d-2668915a1d3a077262c88fab6aa0aa02.ssl.cf3.rackcdn.com/17303281_3_640.jpg',
            price: 18000,
            material: 'gold',
            countInStock: 1,
            brand: 'Rolex',
            rating: 5,
            numReviews: 0,
            description: 'Rolex Datejust Steel Yellow Gold Black Dial Mens Watch 16233. Officially certified chronometer self-winding movement. Stainless steel case 36 mm in diameter. Rolex logo on a 18K yellow gold crown. 18k yellow gold fluted bezel. Scratch resistant sapphire crystal with Cyclops magnifier. Black dial with raised gold baton hour markers. Date window at 3 oclock aperture. Stainless steel and 18k yellow gold jubilee bracelet with fold over clasp. Fits 7.5" wrist.',
        },
        {
            name: 'Rolex Day-date',
            category: 'muski',
            image: 'https://b34959663f5a3997bd0d-2668915a1d3a077262c88fab6aa0aa02.ssl.cf3.rackcdn.com/17302751_3_640.jpg',
            price: 13000,
            material: 'oystersteel',
            countInStock: 12,
            brand: 'Rolex',
            rating: 5,
            numReviews: 0,
            description: 'Rolex Datejust Steel Yellow Gold Black Dial Mens Watch 16233. Officially certified chronometer self-winding movement. Stainless steel case 36 mm in diameter. Rolex logo on a 18K yellow gold crown. 18k yellow gold fluted bezel. Scratch resistant sapphire crystal with Cyclops magnifier. Black dial with raised gold baton hour markers. Date window at 3 oclock aperture. Stainless steel and 18k yellow gold jubilee bracelet with fold over clasp. Fits 7.5" wrist.',
        },
        
        {
            name: 'Rolex Day-just-31 gold',
            category: 'zenski',
            image: 'https://b34959663f5a3997bd0d-2668915a1d3a077262c88fab6aa0aa02.ssl.cf3.rackcdn.com/17303794_3_640.jpg',
            price: 13000,
            material: 'gold',
            countInStock: 12,
            brand: 'Rolex',
            rating: 5,
            numReviews: 0,
            description: 'Rolex Datejust Steel Yellow Gold Black Dial Mens Watch 16233. Officially certified chronometer self-winding movement. Stainless steel case 36 mm in diameter. Rolex logo on a 18K yellow gold crown. 18k yellow gold fluted bezel. Scratch resistant sapphire crystal with Cyclops magnifier. Black dial with raised gold baton hour markers. Date window at 3 oclock aperture. Stainless steel and 18k yellow gold jubilee bracelet with fold over clasp. Fits 7.5" wrist.',
        },
        {
            name: 'Rolex Day-just-31',
            category: 'zenski',
            image: 'https://b34959663f5a3997bd0d-2668915a1d3a077262c88fab6aa0aa02.ssl.cf3.rackcdn.com/17303802_3_640.jpg',
            price: 13000,
            material: 'oystersteel',
            countInStock: 12,
            brand: 'Rolex',
            rating: 5,
            numReviews: 0,
            description: 'Rolex Datejust Steel Yellow Gold Black Dial Mens Watch 16233. Officially certified chronometer self-winding movement. Stainless steel case 36 mm in diameter. Rolex logo on a 18K yellow gold crown. 18k yellow gold fluted bezel. Scratch resistant sapphire crystal with Cyclops magnifier. Black dial with raised gold baton hour markers. Date window at 3 oclock aperture. Stainless steel and 18k yellow gold jubilee bracelet with fold over clasp. Fits 7.5" wrist.',
        },
        {
            name: 'Rolex Perlmaster-34 gold',
            category: 'zenski',
            image: 'https://b34959663f5a3997bd0d-2668915a1d3a077262c88fab6aa0aa02.ssl.cf3.rackcdn.com/17303426_3_640.jpg',
            price: 13000,
            material: 'gold',
            countInStock: 12,
            brand: 'Rolex',
            rating: 5,
            numReviews: 0,
            description: 'Rolex Datejust Steel Yellow Gold Black Dial Mens Watch 16233. Officially certified chronometer self-winding movement. Stainless steel case 36 mm in diameter. Rolex logo on a 18K yellow gold crown. 18k yellow gold fluted bezel. Scratch resistant sapphire crystal with Cyclops magnifier. Black dial with raised gold baton hour markers. Date window at 3 oclock aperture. Stainless steel and 18k yellow gold jubilee bracelet with fold over clasp. Fits 7.5" wrist.',
        },
        {
            name: 'Rolex Perlmaster-34',
            category: 'zenski',
            image: 'https://b34959663f5a3997bd0d-2668915a1d3a077262c88fab6aa0aa02.ssl.cf3.rackcdn.com/17303443_3_640.jpg',
            price: 13000,
            material: 'oystersteel',
            countInStock: 12,
            brand: 'Rolex',
            rating: 5,
            numReviews: 0,
            description: 'Rolex Datejust Steel Yellow Gold Black Dial Mens Watch 16233. Officially certified chronometer self-winding movement. Stainless steel case 36 mm in diameter. Rolex logo on a 18K yellow gold crown. 18k yellow gold fluted bezel. Scratch resistant sapphire crystal with Cyclops magnifier. Black dial with raised gold baton hour markers. Date window at 3 oclock aperture. Stainless steel and 18k yellow gold jubilee bracelet with fold over clasp. Fits 7.5" wrist.',
        },
        {
            name: 'Rolex Lady-datejust gold',
            category: 'zenski',
            image: 'https://b34959663f5a3997bd0d-2668915a1d3a077262c88fab6aa0aa02.ssl.cf3.rackcdn.com/17302745_3_640.jpg',
            price: 13000,
            material: 'gold',
            countInStock: 12,
            brand: 'Rolex',
            rating: 5,
            numReviews: 0,
            description: 'Rolex Datejust Steel Yellow Gold Black Dial Mens Watch 16233. Officially certified chronometer self-winding movement. Stainless steel case 36 mm in diameter. Rolex logo on a 18K yellow gold crown. 18k yellow gold fluted bezel. Scratch resistant sapphire crystal with Cyclops magnifier. Black dial with raised gold baton hour markers. Date window at 3 oclock aperture. Stainless steel and 18k yellow gold jubilee bracelet with fold over clasp. Fits 7.5" wrist.',
        },
        {
            name: 'Rolex Lady-datejust',
            category: 'zenski',
            image: 'https://b34959663f5a3997bd0d-2668915a1d3a077262c88fab6aa0aa02.ssl.cf3.rackcdn.com/17304483_3_640.jpg',
            price: 13000,
            material: 'oystersteel',
            countInStock: 12,
            brand: 'Rolex',
            rating: 5,
            numReviews: 0,
            description: 'Rolex Datejust Steel Yellow Gold Black Dial Mens Watch 16233. Officially certified chronometer self-winding movement. Stainless steel case 36 mm in diameter. Rolex logo on a 18K yellow gold crown. 18k yellow gold fluted bezel. Scratch resistant sapphire crystal with Cyclops magnifier. Black dial with raised gold baton hour markers. Date window at 3 oclock aperture. Stainless steel and 18k yellow gold jubilee bracelet with fold over clasp. Fits 7.5" wrist.',
        },
        {
            name: 'Rolex Lady-datejust-31 gold',
            category: 'zenski',
            image: 'https://b34959663f5a3997bd0d-2668915a1d3a077262c88fab6aa0aa02.ssl.cf3.rackcdn.com/17303110_3_640.jpg',
            price: 13000,
            material: 'gold',
            countInStock: 12,
            brand: 'Rolex',
            rating: 5,
            numReviews: 0,
            description: 'Rolex Datejust Steel Yellow Gold Black Dial Mens Watch 16233. Officially certified chronometer self-winding movement. Stainless steel case 36 mm in diameter. Rolex logo on a 18K yellow gold crown. 18k yellow gold fluted bezel. Scratch resistant sapphire crystal with Cyclops magnifier. Black dial with raised gold baton hour markers. Date window at 3 oclock aperture. Stainless steel and 18k yellow gold jubilee bracelet with fold over clasp. Fits 7.5" wrist.',
        },
        {
            name: 'Rolex Lady-datejust-31',
            category: 'zenski',
            image: 'https://b34959663f5a3997bd0d-2668915a1d3a077262c88fab6aa0aa02.ssl.cf3.rackcdn.com/17303325_3_640.jpg',
            price: 13000,
            material: 'oystersteel',
            countInStock: 12,
            brand: 'Rolex',
            rating: 5,
            numReviews: 0,
            description: 'Rolex Datejust Steel Yellow Gold Black Dial Mens Watch 16233. Officially certified chronometer self-winding movement. Stainless steel case 36 mm in diameter. Rolex logo on a 18K yellow gold crown. 18k yellow gold fluted bezel. Scratch resistant sapphire crystal with Cyclops magnifier. Black dial with raised gold baton hour markers. Date window at 3 oclock aperture. Stainless steel and 18k yellow gold jubilee bracelet with fold over clasp. Fits 7.5" wrist.',
        },
    ],
    
};

export default data;